eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8087
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/citizen_miro
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
    database-platform: org.hibernate.dialect.MySQLDialect
    
  application:
    name: CITIZEN